### ISSUE TITLE
Class ITestRunListener not found

### ISSUE THREAD

**Issue by shawnbertrand** [dpreussler/automator-log-converter#4]
I've tried many different ways to run this jar, especially the documented way, and it just doesn't work.  I keep getting this:

Exception in thread "main" java.lang.NoClassDefFoundError: com/android/ddmlib/testrunner/ITestRunListener
        at de.preusslerpark.android.tools.Runner.convert(Runner.java:52)
        at de.preusslerpark.android.tools.Runner.main(Runner.java:35)
Caused by: java.lang.ClassNotFoundException: com.android.ddmlib.testrunner.ITestRunListener
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

ddmlib.jar is specified on the classpath:

    java -cp . -jar uiautomator2junit-0.3.jar convert output.txt

And it is also in the lib directory within the uiautomator2junit jar file, but it is not specified in the manifest.

What am I doing wrong here?

**Comment by dpreussler** [comment]
Hi, sorry for the late reply.
So I saw just something went wrong with the 0.3 version.
I will repair later today.
You could use the 0.2 version for now or wait for an update.
Sorry about that

**Comment by dpreussler** [comment]
fixed, please use the new jar
